#!/bin/sh
# ── armojidots theme engine ─────────────────────────
# One accent color drives waybar, foot, sway borders, and walker.
#   theme.sh apply <palette>   palettes: wallpaper (extracted from current
#                              wallpaper), ruby, orange, dandelion, emerald,
#                              cobalt, bubblegum, purpur, b&w
#   theme.sh pick              walker picker (used by /set color)
#   theme.sh startup           re-apply saved palette (for autostart)

STATE_DIR="$HOME/.local/state/armojidots"
WALL="$HOME/dotfiles/wallpapers/current"
mkdir -p "$STATE_DIR"

PALETTES="wallpaper
ruby
orange
dandelion
emerald
cobalt
bubblegum
purpur
b&w"

extract_from_wallpaper() {
  python3 - "$WALL" <<'PYEOF'
import sys, colorsys
from PIL import Image

img = Image.open(sys.argv[1]).convert("RGB").resize((64, 64))
best, best_score = None, 0
for count, (r, g, b) in img.getcolors(64 * 64):
    h, s, v = colorsys.rgb_to_hsv(r / 255, g / 255, b / 255)
    score = count * (s ** 1.5) * v
    if v > 0.25 and score > best_score:
        best, best_score = (r, g, b), score
if best is None:
    best = (120, 140, 200)

h, s, v = colorsys.rgb_to_hsv(*[c / 255 for c in best])
s = min(1.0, s * 1.2 + 0.1)          # keep accents punchy and readable
v = min(1.0, max(v, 0.75))
acc = colorsys.hsv_to_rgb(h, s, v)
dim = colorsys.hsv_to_rgb(h, s, v * 0.68)
print("#%02x%02x%02x" % tuple(int(c * 255) for c in acc),
      "#%02x%02x%02x" % tuple(int(c * 255) for c in dim))
PYEOF
}

derive_family() {
  # from one seed color, derive a full palette family:
  # ACC DIM BG BG2 FG MUTED (bg/fg/muted are hue-tinted toward the seed)
  python3 - "$1" <<'PYEOF'
import sys, colorsys

def hx(rgb): return "#%02x%02x%02x" % tuple(int(c * 255) for c in rgb)
r, g, b = (int(sys.argv[1][i:i+2], 16) / 255 for i in (1, 3, 5))
h, s, v = colorsys.rgb_to_hsv(r, g, b)

acc   = colorsys.hsv_to_rgb(h, s, v)
dim   = colorsys.hsv_to_rgb(h, s, v * 0.68)
bg    = colorsys.hsv_to_rgb(h, s * 0.45, 0.09)   # deep tinted background
bg2   = colorsys.hsv_to_rgb(h, s * 0.35, 0.22)   # raised surface / unfocused border
fg    = colorsys.hsv_to_rgb(h, s * 0.08, 0.93)   # near-white, tinted
muted = colorsys.hsv_to_rgb(h, s * 0.18, 0.58)
print(hx(acc), hx(dim), hx(bg), hx(bg2), hx(fg), hx(muted))
PYEOF
}

resolve() {
  case "$1" in
    ruby)      seed="#e35d6a" ;;
    orange)    seed="#f28744" ;;
    dandelion) seed="#f2c94c" ;;
    emerald)   seed="#3ecf82" ;;
    cobalt)    seed="#5480f2" ;;
    bubblegum) seed="#f06ec3" ;;
    purpur)    seed="#a06ef0" ;;
    bw|"b&w")  seed="#e8eaef" ;;
    wallpaper) seed=$(extract_from_wallpaper | cut -d' ' -f1) ;;
    *) return 1 ;;
  esac
  set -- $(derive_family "$seed")
  ACC="$1" DIM="$2" BG="$3" BG2="$4" FG="$5" MUTED="$6"
}

apply() {
  name="$1"
  resolve "$name" || { notify-send "theme" "unknown palette: $name"; exit 1; }

  # ── waybar ──
  bg_r=$((0x${BG#\#} >> 16 & 255)); bg_g=$((0x${BG#\#} >> 8 & 255)); bg_b=$((0x${BG#\#} & 255))
  cat > "$HOME/.config/waybar/colors.css" <<EOF
/* generated by theme.sh — palette: $name */
@define-color accent $ACC;
@define-color accent-dim $DIM;
@define-color bg rgba($bg_r, $bg_g, $bg_b, 0.55);
@define-color fg $FG;
@define-color muted $MUTED;
EOF

  # ── foot (terminal) ──
  cat > "$HOME/.config/foot/colors.ini" <<EOF
# generated by theme.sh — palette: $name
[colors]
alpha=0.88
background=${BG#\#}
foreground=${FG#\#}
selection-foreground=${BG#\#}
selection-background=${ACC#\#}
regular0=${BG2#\#}
regular1=e06c75
regular2=98c379
regular3=e5c07b
regular4=61afef
regular5=c678dd
regular6=56b6c2
regular7=dcdfe4
bright0=${MUTED#\#}
bright1=e06c75
bright2=98c379
bright3=e5c07b
bright4=61afef
bright5=c678dd
bright6=56b6c2
bright7=ffffff
EOF

  # ── sway window borders ──
  cat > "$HOME/.config/sway/colors.conf" <<EOF
# generated by theme.sh — palette: $name
# class                 border  bg      text    indicator child_border
client.focused          $ACC $ACC #ffffff $ACC $ACC
client.focused_inactive $BG2 $BG $MUTED $BG2 $BG2
client.unfocused        $BG2 $BG $MUTED $BG2 $BG2
client.urgent           #e06c75 #e06c75 #ffffff #e06c75 #e06c75
EOF

  # ── walker ──
  cat > "$HOME/.config/walker/themes/armoji/colors.css" <<EOF
/* generated by theme.sh — palette: $name */
@define-color window_bg_color rgba($bg_r, $bg_g, $bg_b, 0.58);
@define-color accent_bg_color $ACC;
@define-color theme_fg_color $FG;
@define-color error_bg_color #C34043;
@define-color error_fg_color #DCD7BA;
EOF

  printf '%s\n' "$name" > "$STATE_DIR/theme"

  # ── reload the world ──
  swaymsg reload >/dev/null 2>&1
  killall waybar 2>/dev/null; swaymsg exec waybar >/dev/null 2>&1
  killall walker 2>/dev/null; swaymsg exec 'walker --gapplication-service' >/dev/null 2>&1
  notify-send -t 3000 "󰏘 Theme" "palette: $name ($ACC)"
}

case "$1" in
  apply)   apply "$2" ;;
  startup) apply "$(cat "$STATE_DIR/theme" 2>/dev/null || echo wallpaper)" ;;
  pick)
    choice=$(printf '%s\n' "$PALETTES" | walker --dmenu -p "color ❯")
    [ -n "$choice" ] && apply "$choice"
    ;;
  *) echo "usage: theme.sh apply <palette> | pick | startup" >&2; exit 1 ;;
esac
